name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:

    runs-on: self-hosted

    steps:
      - name: Check Runner
        run: echo "Hello from my self-hosted runner!"

      - name: Check Windows Machine
        run: |
          hostname
          whoami
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
